### ISSUE TITLE
Update HTTP.jl

### ISSUE THREAD

**Issue by limarta** [cjdoris/HuggingFaceHub.jl#3]
[This error](https://github.com/JuliaWeb/HTTP.jl/issues/1157) is due to the new `Memory` feature in 1.11. HTTP.jl needs to be updated.

**Comment by cjdoris** [comment]
Thanks!

Fixed by: https://github.com/cjdoris/HuggingFaceHub.jl/pull/4

Releasing v0.1.2: https://github.com/JuliaRegistries/General/pull/118242
